# stem for genotype data (bed/bim/fam format)
# refers to clean data
bfile: data/processed/atregmap_clean

# phenotype data
pheno_raw: data/raw/aa360_raw_ratios.csv
pheno_file: data/processed/aa360_BLUEs.txt

# covariates
covar: data/processed/aa360_covars.txt
