# stem for genotype data (bed/bim/fam format)
# refers to clean data
bfile: data/processed/atregmap_clean

# phenotype data
pheno_raw: data/raw/pheno_file
pheno_file: data/raw/pheno_file

# covariates
covar: data/processed/pc_covars
