---
title: "AA-GP: MultiBLUP results"
output: 
  html_notebook:
    toc: yes
    toc_float: yes
date: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: inline
---

## Setup

```{r setup}
knitr::opts_knit$set(root.dir = "~/Documents/AA-GenomicPrediction")

library(tidyverse)
library(broom)
library(quantreg)
```

## Determine MultiBLUP Thresholds

```{r 95 threshold for multiblup}
load("reports/model_summary.RData")
load("reports/gblup.RData")
load("reports/multiblup.RData")
load("reports/null_distribution.RData")

# set pathways to exclude
exclude <-
  c(
    "aa_deg_bcat",
    "aa_syn_nobcat",
    "aa_deg_old",
    "aa_syn_old",
    "asp_protease",
    "cys_protease",
    "degradation_AAA",
    "degradation_autophagy",
    "degradation_subtilases",
    "glycolysis_cystolic",
    "glycolysis_plastid",
    "glycolysis_other",
    "metallo_protease",
    "protein_degradation_old",
    "ser_protease"
  )

pathways <- pathways %>% 
  filter(!pathway %in% exclude)

multiblup_thresholds <- pathways %>%
  group_by(pathway) %>%
  mutate(stat = list(c(h2_95 = as.data.frame(
    lapply(h2_fit,
           function(x)
             tryCatch({
               predict(x,
                       data.frame(size = size))
             }, error = function(err) {
               NA
             }))
  ),
  lr_95 = as.data.frame(
    lapply(lr_fit,
           function(x)
             tryCatch({
               predict(x,
                       data.frame(size = size))
             }, error = function(err) {
               NA
             })))))
  ) %>%
  mutate(stat = map(stat, bind_rows)) %>%
  unnest() %>%
  gather(., id, value, -pathway, -n_genes, -size) %>%
  separate(col = id, into = c("stat", "trait"), sep = "\\.") %>%
  spread(., stat, value)

head(multiblup_thresholds)
  
write_csv(multiblup_thresholds, "reports/multiblup_thresholds.csv")

```

## 'Significant' results

```{r multiblup results}

multiblup_result <- multiblup_summary %>%
  left_join(., gblup_llik) %>%
  left_join(., multiblup_llik) %>% 
  left_join(., gblup_summary) %>% 
  group_by(trait, pathway) %>%
  summarize_if(is.numeric, mean) %>% 
  ungroup() %>% 
  mutate(multiblup_lr = 2*(multiblup_llik - gblup_llik)) %>%
  left_join(., multiblup_thresholds, by = c("trait", "pathway")) %>%
  mutate(lr_pass = multiblup_lr > lr_95,
         h2_pass = multiblup_h2 > h2_95,
         pa_pass = (multiblup_pa - gblup_pa > 0.01),
         pathway = fct_recode(pathway,
                              aa_deg_old = "aa_degradation",
                              aa_syn_old = "aa_synthesis",
                              aa_degradation = "aa_deg_bcat_haplo",
                              aa_synthesis = "aa_syn_nobcat_haplo"
                              )) %>%
  filter(!pathway %in% exclude)

pa_5 <- multiblup_result %>%
  mutate(pa_diff = multiblup_pa - gblup_pa) %>%
  filter(pa_diff >= 0.05,
         lr_pass == TRUE,
         h2_pass == TRUE,
         !pathway %in% exclude)

multiblup_pass <- multiblup_result %>%
  filter(lr_pass == TRUE,
         h2_pass == TRUE,
         pa_pass == TRUE) 

table3 <- multiblup_pass %>% 
  inner_join(aa_fam, ., by = c("trait")) %>%
  mutate(pa_diff = multiblup_pa - gblup_pa,
         reliability_diff = multiblup_reliability - gblup_reliability,
         int_diff = multiblup_bias_int - gblup_bias_int,
         MSE_diff = multiblup_mse - gblup_mse) %>%
  # dplyr::select(trait,
  #               pathway,
  #               multiblup_h2,
  #               lr_pass,
  #               h2_pass,
  #               pa_pass,
  #               aa_cat,
  #               family) %>%
  mutate(
    aa_cat = fct_relevel(aa_cat, "absolute", "relative", "family"),
    category = ifelse(
      grepl("degradation_|protein_|protease", pathway),
      "protein",
      ifelse(
        grepl(
          "flavonoids|isoprenoids|N_containing|phenylpropanoids|S_containing",
          pathway
        ),
        "specialized",
        ifelse(
          grepl("aa_degradation|aa_synthesis|aa_transport", pathway),
          "amino acid",
          "primary"
        )
      )
    ) ,
    category = factor(
      category,
      levels = c("amino acid", "primary", "specialized", "protein")
    )
  ) %>%
  select(aa_cat, category, pathway, trait, h2_95, multiblup_h2, lr_95, multiblup_lr, 
         pa_diff, reliability_diff, gblup_bias_int, multiblup_bias_int,
         gblup_bias_slope, multiblup_bias_slope, gblup_mse, multiblup_mse) %>%
  distinct() %>% 
  arrange(category, trait) %>%
  write_csv("reports/table3.csv")

```
